import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>星星问卷</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/stars.svg' />
      </Head>
      <main className={'flex flex-col items-center justify-center h-screen'}>
        <h1>～～此路不通～～</h1>
        <h3>还是麻烦您，通过正经渠道进来吧...</h3>
      </main>
    </>
  );
}
